name: Maven Package
on:
  push:
    branches:
      - vp-rem
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repoitry/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn package

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region, e.g., us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build Dcoker Image
      run: |
       docker image prune  -f -a
       docker build -t vpro .
       docker tag vpro:latest 098024363174.dkr.ecr.us-east-1.amazonaws.com/app1:latest
       
    - name: push Docker image
      run: |
          docker push 098024363174.dkr.ecr.us-east-1.amazonaws.com/app1:latest
          aws ecs describe-task-definition --task-definition app --query taskDefinition --region us-east-1 > task-definition.json


   
